# Generated by Django 3.2 on 2021-04-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='statuses',
            new_name='status',
        ),
    ]
